spring.application.name=AccesoUsuarios

# Si está en Railway usa la variable; si estás en tu PC local, usa localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_AccesoUsuarios}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Si está en Railway usa el puerto asignado; en tu PC local usa el 8080
server.port=${PORT:8080}

server.servlet.session.timeout=30m
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=30MB
spring.thymeleaf.cache=false