package com.agroconecta.app.ui.navigation

sealed class AppDestination(val route: String) {
    data object Login : AppDestination("login")
    data object Register : AppDestination("register")
    data object Tienda : AppDestination("tienda")
    data object Home : AppDestination("home")
    data object ProductoDetail : AppDestination("producto_detail")
    data object CampesinoPerfil : AppDestination("campesino_perfil")
    data object Carrito : AppDestination("carrito")
    data object Perfil : AppDestination("perfil")
    data object Direcciones : AppDestination("direcciones")
    data object Resenas : AppDestination("resenas")
    data object Favoritos : AppDestination("favoritos")
    data object MisCompras : AppDestination("mis_compras")
    data object Checkout : AppDestination("checkout")
    data object CompraExitosa : AppDestination("compra_exitosa")
    data object CampesinoDashboard : AppDestination("campesino_dashboard")
    data object CampesinoProductos : AppDestination("campesino_productos")
    data object ProductoForm : AppDestination("producto_form")
    data object Sipsa : AppDestination("sipsa")
    data object Inventario : AppDestination("inventario")
    data object PedidosCampesino : AppDestination("pedidos_campesino")
    data object Analiticas : AppDestination("analiticas")
    data object Reputacion : AppDestination("reputacion")
    data object Finanzas : AppDestination("finanzas")
    data object Logistica : AppDestination("logistica")
    data object CampesinoPerfilEdit : AppDestination("campesino_perfil_edit")
    data object Soporte : AppDestination("soporte")
    data object CampesinoVerificacion : AppDestination("campesino_verificacion")
}
